[profile.default]
src              = "src"
out              = "out"
libs             = ["lib"]
optimizer        = true
via_ir           = true
optimizer_runs   = 200
evm_version      = "cancun"

[profile.release]
via_ir           = true
optimizer        = true
optimizer_runs   = 10_000
evm_version      = "cancun"
bytecode_hash    = "none"